version: '3.8'
networks:
    mjml-docker-bridge:
        external: true
volumes:
    node_modules:
services:
    mjml:
        image: mjml-server:dev
        networks:
            - mjml-docker-bridge
        ports:
            - "8031:80"
        volumes:
            - ./server.js:/app/server.js

    yarn:
        build:
            context: .
        volumes:
            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - node_modules:/app/node_modules
        entrypoint: /usr/local/bin/yarn