name: Application image build

on:
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build_mjml:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase github.repository
        run: |
          echo "CONTAINER_URL=ghcr.io/${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push php image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.CONTAINER_URL }}:${{ github.event.pull_request.head.sha }}
          cache-from: |
            type=gha
#            type=registry,ref=${{ env.CONTAINER_URL }}/php:cache
          cache-to: |
            type=gha
#            type=registry,ref=${{ env.CONTAINER_URL }}/php:cache,mode=max
#          labels: ${{ steps.meta.outputs.labels }}
